export const CONTEXT_ACTION = {
    SET_USER: 'SET_USER',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    LOGOUT: 'LOGOUT',
    TOGGLE_THEME: 'TOGGLE_THEME',
    CHECK_LOGIN_STATUS: 'CHECK_LOGIN_STATUS',
};
