// import TransactionsList from "@/app/(hydrogen)/widgets/cards/transactions-list";
//
// export const routes = {
//   dashboard: "/",
//   activities: "/activities",
//   notifications: "/profile/notifications",
//   management: {
//     dashboard: "/management",
//     requestList: '/management/request-list',
//   },
//   eCommerce: {
//     dashboard: '/ecommerce',
//     products: '/ecommerce/products',
//     createProduct: '/ecommerce/products/create',
//     productDetails: (id: string) => `/ecommerce/products/${id}`,
//     ediProduct: (id: string) => `/ecommerce/products/${id}/edit`,
//     categories: '/ecommerce/categories',
//     createCategory: '/ecommerce/categories/create',
//     editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
//     orders: '/ecommerce/orders',
//     createOrder: '/ecommerce/orders/create',
//     orderDetails: (id: string) => `/ecommerce/orders/${id}`,
//     editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
//     reviews: '/ecommerce/reviews',
//     shop: '/ecommerce/shop',
//     cart: '/ecommerce/cart',
//     checkout: '/ecommerce/checkout',
//     trackingId: (id: string) => `/ecommerce/tracking/${id}`,
//   },
//   foodIndustry: {
//     dashboard: '/food-industry',
//     products: '/food-industry/products',
//     createProduct: '/food-industry/products/create',
//     productDetails: (id: string) => `/food-industry/products/${id}`,
//     ediProduct: (id: string) => `/food-industry/products/${id}/edit`,
//     categories: '/food-industry/categories',
//     createCategory: '/food-industry/categories/create',
//     editCategory: (id: string) => `/food-industry/categories/${id}/edit`,
//     orders: '/food-industry/orders',
//     createOrder: '/food-industry/orders/create',
//     orderDetails: (id: string) => `/food-industry/orders/${id}`,
//     editOrder: (id: string) => `/food-industry/orders/${id}/edit`,
//     reviews: '/food-industry/reviews',
//     shop: '/food-industry/shop',
//     cart: '/food-industry/cart',
//     checkout: '/food-industry/checkout',
//     trackingId: (id: string) => `/food-industry/tracking/${id}`,
//   },
//   info: {
//     dashboard: '/info',
//     mediaBankList: '/info/media',
//     mediaBankAdd: '/info/media/create',
//     mediaBankView: (id: number) => `/info/media/${id}`,
//     mediaBankEdit: (id: number) => `/info/media/${id}/edit`,
//     foodIndustryList: '/info/food-industry',
//     foodIndustryAdd: '/info/food-industry/create',
//     foodIndustryView: (id: number) => `/info/food-industry/${id}`,
//     foodIndustryEdit: (id: number) => `/info/food-industry/${id}/edit`,
//     agricultureIndustryList: '/info/agriculture-industry',
//     agricultureIndustryAdd: '/info/agriculture-industry/create',
//     agricultureIndustryView: (id: number) => `/info/agriculture-industry/${id}`,
//     agricultureIndustryEdit: (id: number) =>
//       `/info/agriculture-industry/${id}/edit`,
//     machinery: '/info/machinery/',
//     machineryBuyerList: '/info/machinery/buyer',
//     machineryBuyerAdd: '/info/machinery/buyer/create',
//     machineryBuyerEdit: (id: number) => `/info/machinery/buyer/${id}/edit`,
//     machinerySellerList: '/info/machinery/seller',
//     machinerySellerAdd: '/info/machinery/seller/create',
//     machinerySellerEdit: (id: number) => `/info/machinery/seller/${id}/edit`,
//     // machineryView: (id: number) => `/info/machinery/${id}`,
//     // machineryEdit: (id: number) => `/info/machinery/${id}/edit`,
//     serviceBank: '/info/service',
//     exhibitionList: '/info/service/exhibitions/list',
//     exhibitionAdd: '/info/service/exhibitions/create',
//     exhibitionEdit: (id: number) => `/info/service/exhibitions/${id}/edit`,
//     serviceIndustryList: '/info/service',
//     serviceIndustryAdd: '/info/service/create',
//     serviceIndustryView: (id: number) => `/info/service/${id}`,
//     serviceIndustryEdit: (subCategory: string, id: number) => `/info/service/${subCategory}/${id}/edit`,
//     serviceIndustrySubCategoryList: (id: number) => `/info/service/subcategory/${id}`,
//     media: '/info/media',
//     machineryIndustry: '/info/machinery-industry',
//     // dashboard: '/company',
//     profile: '/profile',
//     profileEdit: '/profile/edit',
//     profilePassword: '/profile/password',
//     profileNotification: '/profile/notification',
//     products: '/company/products',
//     createProduct: '/company/products/create',
//     productDetails: (id: string) => `/company/products/${id}`,
//     ediProduct: (id: string) => `/company/products/${id}/edit`,
//     categories: '/company/categories',
//     createCategory: '/company/categories/create',
//     editCategory: (id: string) => `/company/categories/${id}/edit`,
//     orders: '/company/orders',
//     createOrder: '/company/orders/create',
//     orderDetails: (id: string) => `/company/orders/${id}`,
//     editOrder: (id: string) => `/company/orders/${id}/edit`,
//     reviews: '/company/reviews',
//     shop: '/company/shop',
//     cart: '/company/cart',
//     checkout: '/company/checkout',
//     trackingId: (id: string) => `/company/tracking/${id}`,
//     exhibitionsCreate: '/info/service/exhibitions/create',
//     conferencesCreate: '/info/service/conferences/create',
//     employmentCreate: '/info/service/employment/create',
//     jobsCreate: '/info/service/jobs/create',
//     requestCreate: '/info/service/request/create',
//     resellerCreate: '/info/service/reseller/create',
//     labsCreate: '/info/service/labs/create',
//     certificationsCreate: '/info/service/certification/create',
//     saleFactoryEdit: (id: number) => `/info/service/sale_factory/${id}/edit`,
//     saleFactoryCreate: '/info/service/sale_factory/create',
//     surplusEdit: (id: number) => `/info/service/surplus/${id}/edit`,
//     surplusCreate: '/info/service/surplus/create',
//     associationsEdit: (id: number) => `/info/service/associations/${id}/edit`,
//     associationsCreate: '/info/service/associations/create',
//   },
//   finance: {
//     dashboard: '/finance',
//     wallet: '/finance/wallet',
//     paymentList: '/finance/payment',
//     paymentDetails: (id: string) => `/finance/payment/${id}`,
//     transactionDetails: (id: string) => `/finance/transaction/${id}`,
//     transactionList: '/finance/transaction',
//     invoiceList: '/finance/invoice',
//     invoiceDetails: (id: string) => `/finance/invoice/${id}`,
//     invoiceEdit: (id: string) => `/finance/invoice/${id}/edit`,
//     invoiceCreate: '/finance/invoice/create',
//     // list: '/finance/list',
//     // view: (id: string) => `/finance/list/${id}`,
//   },
//   wallet: {
//     main: '/finance/wallet',
//   },
//   payment: {
//     list: '/finance/payment',
//     view: (id: string) => `/finance/payment/${id}`,
//   },
//   // invoice: {
//   //   list: '/finance/invoice/list',
//   //   view: (id: string) => `/finance/invoice/list/${id}`,
//   // },
//   invoice: {
//     home: '/finance/invoice',
//     create: '/finance/invoice/create',
//     details: (id: string) => `/finance/invoice/${id}`,
//     edit: (id: string) => `/finance/invoice/${id}/edit`,
//   },
//   offer: {
//     dashboard: '/offer',
//     list: '/offer/list',
//     view: (id: string) => `/offer/list/${id}`,
//     buy: (id: string) => `/offer/buy/${id}`,
//   },
//   support: {
//     dashboard: '/support',
//     inbox: '/support/inbox',
//     supportCategory: (category: string) => `/support/inbox/${category}`,
//     messageDetails: (id: string) => `/support/inbox/${id}`,
//     snippets: '/support/snippets',
//     createSnippet: '/support/snippets/create',
//     viewSnippet: (id: string) => `/support/snippets/${id}`,
//     editSnippet: (id: string) => `/support/snippets/${id}/edit`,
//     templates: '/support/templates',
//     createTemplate: '/support/templates/create',
//     viewTemplate: (id: string) => `/support/templates/${id}`,
//     editTemplate: (id: string) => `/support/templates/${id}/edit`,
//     ticket: '/support/ticket',
//   },
//   logistics: {
//     dashboard: '/logistics',
//     shipmentList: '/logistics/shipments',
//     customerProfile: '/logistics/customer-profile',
//     createShipment: '/logistics/shipments/create',
//     shipmentDetails: '/logistics/shipments/details',
//     tracking: (id: string) => `/logistics/tracking/${id}`,
//   },
//   analytics: '/analytics',
//   file: {
//     dashboard: '/file',
//     manager: '/file-manager',
//     upload: '/file-manager/upload',
//     create: '/file-manager/create',
//   },
//   widgets: {
//     cards: '/widgets/cards',
//     icons: '/widgets/icons',
//     charts: '/widgets/charts',
//     maps: '/widgets/maps',
//     banners: '/widgets/banners',
//   },
//   tables: {
//     basic: '/tables/basic',
//     collapsible: '/tables/collapsible',
//     enhanced: '/tables/enhanced',
//     pagination: '/tables/pagination',
//     search: '/tables/search',
//     stickyHeader: '/tables/sticky-header',
//   },
//   multiStep: '/multi-step',
//   forms: {
//     profileSettings: '/forms/profile-settings',
//     notificationPreference: '/forms/profile-settings/notification',
//     personalInformation: '/forms/profile-settings/profile',
//     newsletter: '/forms/newsletter',
//   },
//   search: {
//     realEstate: '/search/real-estate',
//   },
//   profile: '/profile',
//   welcome: '/welcome',
//   comingSoon: '/coming-soon',
//   accessDenied: '/access-denied',
//   notFound: '/not-found',
//   maintenance: '/maintenance',
//   blank: '/blank',
//   auth: {
//     signUp1: '/sign-up',
//     signUp2: '/auth/sign-up-2',
//     signUp3: '/auth/sign-up-3',
//     signUp4: '/auth/sign-up-4',
//     signUp5: '/auth/sign-up-5',
//     // sign in
//     signIn1: '/auth/sign-in-1',
//     signIn2: '/auth/sign-in-2',
//     signIn3: '/auth/sign-in-3',
//     signIn4: '/auth/sign-in-4',
//     signIn5: '/auth/sign-in-5',
//     // forgot password
//     forgotPassword1: '/forgot-password',
//     forgotPassword2: '/auth/forgot-password-2',
//     forgotPassword3: '/auth/forgot-password-3',
//     forgotPassword4: '/auth/forgot-password-4',
//     forgotPassword5: '/auth/forgot-password-5',
//     // OTP
//     otp1: '/auth/otp-1',
//     otp2: '/auth/otp-2',
//     otp3: '/auth/otp-3',
//     otp4: '/auth/otp-4',
//     otp5: '/auth/otp-5',
//   },
//   subscriptionList: '/bundle/subscription-list',
//   subscription: (id: number) => `/bundle/${id}`,
//   bundle: (id: number) => `/bundle/${id}/buy`,
//   signIn: '/login',
//   otp: '/login/otp',
// };


import TransactionsList from "@/app/(hydrogen)/widgets/cards/transactions-list";

export const routes = {
    dashboard: "/",
    activities: "/activities",
    notifications: "/profile/notifications",
    management: {
        dashboard: "/management",
        requestList: '/management/request-list',
    },
    eCommerce: {
        dashboard: '/ecommerce',
        products: '/ecommerce/products',
        createProduct: '/ecommerce/products/create',
        productDetails: (id: string) => `/ecommerce/products/${id}`,
        ediProduct: (id: string) => `/ecommerce/products/${id}/edit`,
        categories: '/ecommerce/categories',
        createCategory: '/ecommerce/categories/create',
        editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
        orders: '/ecommerce/orders',
        createOrder: '/ecommerce/orders/create',
        orderDetails: (id: string) => `/ecommerce/orders/${id}`,
        editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
        reviews: '/ecommerce/reviews',
        shop: '/ecommerce/shop',
        cart: '/ecommerce/cart',
        checkout: '/ecommerce/checkout',
        trackingId: (id: string) => `/ecommerce/tracking/${id}`,
    },
    foodIndustry: {
        dashboard: '/food-industry',
        products: '/food-industry/products',
        createProduct: '/food-industry/products/create',
        productDetails: (id: string) => `/food-industry/products/${id}`,
        ediProduct: (id: string) => `/food-industry/products/${id}/edit`,
        categories: '/food-industry/categories',
        createCategory: '/food-industry/categories/create',
        editCategory: (id: string) => `/food-industry/categories/${id}/edit`,
        orders: '/food-industry/orders',
        createOrder: '/food-industry/orders/create',
        orderDetails: (id: string) => `/food-industry/orders/${id}`,
        editOrder: (id: string) => `/food-industry/orders/${id}/edit`,
        reviews: '/food-industry/reviews',
        shop: '/food-industry/shop',
        cart: '/food-industry/cart',
        checkout: '/food-industry/checkout',
        trackingId: (id: string) => `/food-industry/tracking/${id}`,
    },
    info: {
        dashboard: '/info',
        mediaBankList: '/info/media',
        mediaBankAdd: '/info/media/create',
        mediaBankView: (id: number) => `/info/media/${id}`,
        mediaBankEdit: (id: number) => `/info/media/${id}/edit`,
        foodIndustryList: '/info/food-industry',
        foodIndustryAdd: '/info/food-industry/create',
        foodIndustryView: (id: number) => `/info/food-industry/${id}`,
        foodIndustryEdit: (id: number) => `/info/food-industry/${id}/edit`,
        agricultureIndustryList: '/info/agriculture-industry',
        agricultureIndustryAdd: '/info/agriculture-industry/create',
        agricultureIndustryView: (id: number) => `/info/agriculture-industry/${id}`,
        agricultureIndustryEdit: (id: number) =>
            `/info/agriculture-industry/${id}/edit`,
        machinery: '/info/machinery/',
        machineryBuyerList: '/info/machinery/buyer',
        machineryBuyerAdd: '/info/machinery/buyer/create',
        machineryBuyerEdit: (id: number) => `/info/machinery/buyer/${id}/edit`,
        machinerySellerList: '/info/machinery/seller',
        machinerySellerAdd: '/info/machinery/seller/create',
        machinerySellerEdit: (id: number) => `/info/machinery/seller/${id}/edit`,
        // machineryView: (id: number) => `/info/machinery/${id}`,
        // machineryEdit: (id: number) => `/info/machinery/${id}/edit`,
        serviceBank: '/info/service',
        exhibitionList: '/info/service/exhibitions/list',
        exhibitionAdd: '/info/service/exhibitions/create',
        exhibitionEdit: (id: number) => `/info/service/exhibitions/${id}/edit`,
        serviceIndustryList: '/info/service',
        serviceIndustryAdd: '/info/service/create',
        serviceIndustryView: (id: number) => `/info/service/${id}`,
        serviceIndustryEdit: (subCategory: string, id: number) => `/info/service/${subCategory}/${id}/edit`,
        serviceIndustrySubCategoryList: (subCategoryName: string) => `/info/service/${subCategoryName}/list`,
        serviceIndustrySubCategoryCreate: (subCategoryName: string) => `/info/service/${subCategoryName}/create`,

        // Existing routes
        media: '/info/media',
        machineryIndustry: '/info/machinery-industry',
        profile: '/profile',
        profileEdit: '/profile/edit',
        profilePassword: '/profile/password',
        profileNotification: '/profile/notification',
        products: '/company/products',
        createProduct: '/company/products/create',
        productDetails: (id: string) => `/company/products/${id}`,
        ediProduct: (id: string) => `/company/products/${id}/edit`,
        categories: '/company/categories',
        createCategory: '/company/categories/create',
        editCategory: (id: string) => `/company/categories/${id}/edit`,
        orders: '/company/orders',
        createOrder: '/company/orders/create',
        orderDetails: (id: string) => `/company/orders/${id}`,
        editOrder: (id: string) => `/company/orders/${id}/edit`,
        reviews: '/company/reviews',
        shop: '/company/shop',
        cart: '/company/cart',
        checkout: '/company/checkout',
        trackingId: (id: string) => `/company/tracking/${id}`,
        exhibitionsCreate: '/info/service/exhibitions/create',
        conferencesCreate: '/info/service/conferences/create',
        employmentCreate: '/info/service/employment/create',
        jobsCreate: '/info/service/jobs/create',
        requestCreate: '/info/service/request/create',
        resellerCreate: '/info/service/reseller/create',
        labsCreate: '/info/service/labs/create',
        certificationsCreate: '/info/service/certification/create',
        saleFactoryEdit: (id: number) => `/info/service/sale_factory/${id}/edit`,
        saleFactoryCreate: '/info/service/sale_factory/create',
        surplusEdit: (id: number) => `/info/service/surplus/${id}/edit`,
        surplusCreate: '/info/service/surplus/create',
        associationsEdit: (id: number) => `/info/service/associations/${id}/edit`,
        associationsCreate: '/info/service/associations/create',
    },
    finance: {
        dashboard: '/finance',
        wallet: '/finance/wallet',
        paymentList: '/finance/payment',
        paymentDetails: (id: string) => `/finance/payment/${id}`,
        transactionDetails: (id: string) => `/finance/transaction/${id}`,
        transactionList: '/finance/transaction',
        invoiceList: '/finance/invoice',
        invoiceDetails: (id: string) => `/finance/invoice/${id}`,
        invoiceEdit: (id: string) => `/finance/invoice/${id}/edit`,
        invoiceCreate: '/finance/invoice/create',
    },
    wallet: {
        main: '/finance/wallet',
    },
    payment: {
        list: '/finance/payment',
        view: (id: string) => `/finance/payment/${id}`,
    },
    invoice: {
        home: '/finance/invoice',
        create: '/finance/invoice/create',
        details: (id: string) => `/finance/invoice/${id}`,
        edit: (id: string) => `/finance/invoice/${id}/edit`,
    },
    offer: {
        dashboard: '/offer',
        list: '/offer/list',
        view: (id: string) => `/offer/list/${id}`,
        buy: (id: string) => `/offer/buy/${id}`,
    },
    support: {
        dashboard: '/support',
        inbox: '/support/inbox',
        supportCategory: (category: string) => `/support/inbox/${category}`,
        messageDetails: (id: string) => `/support/inbox/${id}`,
        snippets: '/support/snippets',
        createSnippet: '/support/snippets/create',
        viewSnippet: (id: string) => `/support/snippets/${id}`,
        editSnippet: (id: string) => `/support/snippets/${id}/edit`,
        templates: '/support/templates',
        createTemplate: '/support/templates/create',
        viewTemplate: (id: string) => `/support/templates/${id}`,
        editTemplate: (id: string) => `/support/templates/${id}/edit`,
        ticket: '/support/ticket',
    },
    logistics: {
        dashboard: '/logistics',
        shipmentList: '/logistics/shipments',
        customerProfile: '/logistics/customer-profile',
        createShipment: '/logistics/shipments/create',
        shipmentDetails: '/logistics/shipments/details',
        tracking: (id: string) => `/logistics/tracking/${id}`,
    },
    analytics: '/analytics',
    file: {
        dashboard: '/file',
        manager: '/file-manager',
        upload: '/file-manager/upload',
        create: '/file-manager/create',
    },
    widgets: {
        cards: '/widgets/cards',
        icons: '/widgets/icons',
        charts: '/widgets/charts',
        maps: '/widgets/maps',
        banners: '/widgets/banners',
    },
    tables: {
        basic: '/tables/basic',
        collapsible: '/tables/collapsible',
        enhanced: '/tables/enhanced',
        pagination: '/tables/pagination',
        search: '/tables/search',
        stickyHeader: '/tables/sticky-header',
    },
    multiStep: '/multi-step',
    forms: {
        profileSettings: '/forms/profile-settings',
        notificationPreference: '/forms/profile-settings/notification',
        personalInformation: '/forms/profile-settings/profile',
        newsletter: '/forms/newsletter',
    },
    search: {
        realEstate: '/search/real-estate',
    },
    profile: '/profile',
    welcome: '/welcome',
    comingSoon: '/coming-soon',
    accessDenied: '/access-denied',
    notFound: '/not-found',
    maintenance: '/maintenance',
    blank: '/blank',
    auth: {
        signUp1: '/sign-up',
        signUp2: '/auth/sign-up-2',
        signUp3: '/auth/sign-up-3',
        signUp4: '/auth/sign-up-4',
        signUp5: '/auth/sign-up-5',
        // sign in
        signIn1: '/auth/sign-in-1',
        signIn2: '/auth/sign-in-2',
        signIn3: '/auth/sign-in-3',
        signIn4: '/auth/sign-in-4',
        signIn5: '/auth/sign-in-5',
        // forgot password
        forgotPassword1: '/forgot-password',
        forgotPassword2: '/auth/forgot-password-2',
        forgotPassword3: '/auth/forgot-password-3',
        forgotPassword4: '/auth/forgot-password-4',
        forgotPassword5: '/auth/forgot-password-5',
        // OTP
        otp1: '/auth/otp-1',
        otp2: '/auth/otp-2',
        otp3: '/auth/otp-3',
        otp4: '/auth/otp-4',
        otp5: '/auth/otp-5',
    },
    subscriptionList: '/bundle/subscription-list',
    subscription: (id: number) => `/bundle/${id}`,
    bundle: (id: number) => `/bundle/${id}/buy`,
    signIn: '/login',
    otp: '/login/otp',
};